export const PRODUCT_LIST_REAQUEST="PRODUCT_LIST_REAQUEST";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REAQUEST="PRODUCT_DETAIL_REAQUEST";
export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL";

export const PRODUCT_DELETE_REAQUEST="PRODUCT_DELETE_REAQUEST";
export const PRODUCT_DELETE_SUCCESS="PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL="PRODUCT_DELETE_FAIL";


export const PRODUCT_CREATE_REAQUEST="PRODUCT_CREATE_REAQUEST";
export const PRODUCT_CREATE_SUCCESS="PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL="PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET="PRODUCT_CREATE_RESET";


export const PRODUCT_CREATE_REVIEW_REAQUEST="PRODUCT_CREATE_REVIEW_REAQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS="PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL="PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET="PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_TOP_REAQUEST="PRODUCT_TOP_REAQUEST";
export const PRODUCT_TOP_SUCCESS="PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL="PRODUCT_TOP_FAIL";
